# Generated by Django 4.0.1 on 2022-01-27 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_receita_data_receita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='nome',
            new_name='nome_receita',
        ),
    ]
