# Generated by Django 4.0.1 on 2022-01-31 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('app', '0003_rename_nome_receita_nome_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='pessoa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.pessoa'),
            preserve_default=False,
        ),
    ]
